//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Transforms : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Transform
        {
            get
            {
                return SteamVR_Actions.transforms_Transform;
            }
        }
        
        public virtual SteamVR_Action_Boolean Inverse
        {
            get
            {
                return SteamVR_Actions.transforms_Inverse;
            }
        }
        
        public virtual SteamVR_Action_Boolean EquipMenu
        {
            get
            {
                return SteamVR_Actions.transforms_EquipMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.transforms_Teleport;
            }
        }
    }
}
